services:
  walle:
    container_name: bot-walle
    build: .
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./temp_images:/app/temp_images
      - ./webhook_cert.pem:/app/webhook_cert.pem:ro
      - ./webhook_pkey.pem:/app/webhook_pkey.pem:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
